Change to zone less change detection
Tests produced lots of

    ERROR: Error: Acquiring an exclusive Navigator LockManager lock "lock:sb-localhost-auth-token" immediately failed

messages.

https://github.com/supabase/auth-js/issues/830#issuecomment-2627637170